// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLxXjlSoMdsQWTyLY3vjlu6uVVS9tqT8',
    appId: '1:1054184132510:web:0c602cfd77f16b28aad08f',
    messagingSenderId: '1054184132510',
    projectId: 'peers-hackathon',
    authDomain: 'peers-hackathon.firebaseapp.com',
    storageBucket: 'peers-hackathon.firebasestorage.app',
    measurementId: 'G-YJGCYEQR3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkiyC9KWeE_L7xi-AO4GvWxrrlHX_s9c',
    appId: '1:1054184132510:android:c9545c61e96b5e0eaad08f',
    messagingSenderId: '1054184132510',
    projectId: 'peers-hackathon',
    storageBucket: 'peers-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlYBwU_oaLhMhWJ4Q3b-C77NcLqb-D8DE',
    appId: '1:1054184132510:ios:b2e49a5fe760ef65aad08f',
    messagingSenderId: '1054184132510',
    projectId: 'peers-hackathon',
    storageBucket: 'peers-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.peers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlYBwU_oaLhMhWJ4Q3b-C77NcLqb-D8DE',
    appId: '1:1054184132510:ios:b2e49a5fe760ef65aad08f',
    messagingSenderId: '1054184132510',
    projectId: 'peers-hackathon',
    storageBucket: 'peers-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.peers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhLxXjlSoMdsQWTyLY3vjlu6uVVS9tqT8',
    appId: '1:1054184132510:web:de1a35a0b5405853aad08f',
    messagingSenderId: '1054184132510',
    projectId: 'peers-hackathon',
    authDomain: 'peers-hackathon.firebaseapp.com',
    storageBucket: 'peers-hackathon.firebasestorage.app',
    measurementId: 'G-J95KDK8QJC',
  );
}
